"""initial_schema

Revision ID: 95c3bb1ecdcc
Revises: None
Create Date: 2026-04-13 20:52:49.716432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95c3bb1ecdcc'
down_revision: str = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_empresa', sa.String(length=200), nullable=False),
    sa.Column('tipo_cliente', sa.String(length=50), nullable=False),
    sa.Column('nivel_precio', sa.String(length=20), nullable=False),
    sa.Column('descuento_min_porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('descuento_max_porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('markup_personalizado', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('exento_iva', sa.Boolean(), nullable=False),
    sa.Column('notas_pricing', sa.Text(), nullable=True),
    sa.Column('es_recurrente', sa.Boolean(), nullable=False),
    sa.Column('servicios_confirmados', sa.Integer(), nullable=False),
    sa.Column('ultima_cotizacion', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_empresa')
    )
    op.create_table('recargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('idioma_origen', sa.String(length=50), nullable=True),
    sa.Column('idioma_destino', sa.String(length=50), nullable=True),
    sa.Column('precio_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_cliente', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unidad_cobro', sa.String(length=20), nullable=False),
    sa.Column('num_interpretes_default', sa.Integer(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarifas_alquiler_equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_equipo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cantidad_min', sa.Integer(), nullable=False),
    sa.Column('cantidad_max', sa.Integer(), nullable=False),
    sa.Column('num_dias', sa.Integer(), nullable=True),
    sa.Column('precio_base', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('precio_cliente', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contactos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('telefono_whatsapp', sa.String(length=20), nullable=True),
    sa.Column('nombre_temporal', sa.String(length=100), nullable=True),
    sa.Column('ultimo_mensaje_preview', sa.Text(), nullable=True),
    sa.Column('ultimo_mensaje_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mensajes_no_leidos', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cotizaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('contacto_id', sa.Integer(), nullable=True),
    sa.Column('numero_cotizacion', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('ubicacion_evento', sa.String(length=200), nullable=True),
    sa.Column('es_fuera_de_bogota', sa.Boolean(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('exento_iva', sa.Boolean(), nullable=False),
    sa.Column('validez_oferta', sa.String(length=200), nullable=True),
    sa.Column('forma_pago', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('notas_internas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['contacto_id'], ['contactos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_cotizacion')
    )
    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversacion_id', sa.Integer(), nullable=False),
    sa.Column('origen', sa.String(length=20), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('tipo_contenido', sa.String(length=20), nullable=False),
    sa.Column('url_archivo', sa.Text(), nullable=True),
    sa.Column('whatsapp_message_id', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_message_id')
    )
    op.create_table('lineas_cotizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('equipo_alquiler_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fecha_servicio_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_servicio_fin', sa.Date(), nullable=True),
    sa.Column('horario', sa.String(length=100), nullable=True),
    sa.Column('num_interpretes', sa.Integer(), nullable=True),
    sa.Column('num_equipos', sa.Integer(), nullable=True),
    sa.Column('descripcion_generada', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipo_alquiler_id'], ['tarifas_alquiler_equipos.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordenes_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('numero_os', sa.String(length=20), nullable=True),
    sa.Column('fecha_emision', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_os')
    )
    op.create_table('seguimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('fecha_seguimiento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metodo', sa.String(length=50), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('proximo_seguimiento', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitudes_agente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('cotizacion_id', sa.Integer(), nullable=True),
    sa.Column('conversacion_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('prioridad', sa.String(length=10), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('datos_formulario', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('respuesta_encargada', sa.Text(), nullable=True),
    sa.Column('archivo_adjunto', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resuelta_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversaciones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('versiones_cotizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=10), nullable=False),
    sa.Column('total_anterior', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_nuevo', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('motivo_cambio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensajes_internos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('origen', sa.String(length=20), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('tipo_contenido', sa.String(length=20), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes_agente.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensajes_internos')
    op.drop_table('versiones_cotizacion')
    op.drop_table('solicitudes_agente')
    op.drop_table('seguimientos')
    op.drop_table('ordenes_servicio')
    op.drop_table('lineas_cotizacion')
    op.drop_table('mensajes')
    op.drop_table('cotizaciones')
    op.drop_table('conversaciones')
    op.drop_table('contactos')
    op.drop_table('tarifas_alquiler_equipos')
    op.drop_table('servicios')
    op.drop_table('recargos')
    op.drop_table('clientes')
    # ### end Alembic commands ###
